name: Replicate Main

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  replicate-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check PAT Token
      run: |
        if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
          echo "PAT_TOKEN is empty or not set"
          exit 1
        else
          echo "PAT_TOKEN is set"
        fi

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Update develop branch
      run: |
        git checkout develop
        git merge main --no-ff --no-edit
        git push origin develop
