name: Update Tag Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'release'

jobs:
  tag-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
      - name: Get latest tag from main
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV

      - name: Increment major version and create release tag
        id: create_tag
        run: |
          latest_tag=${{ env.LATEST_TAG }}
          major_version=$(echo $latest_tag | awk -F. '{print $1}')
          new_tag="$((major_version + 1)).0-rc"
          echo "NEW_TAG=${new_tag}" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Output new tag
        run: echo "New tag created: ${{ env.NEW_TAG }}"