name: Update Tag Feat

on:
  create:
    branches:
      - 'feat/*'
    branches-ignore:
      - 'develop'
      - 'release'

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check PAT Token
      run: |
        if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
          echo "PAT_TOKEN is empty or not set"
          exit 1
        else
          echo "PAT_TOKEN is set"
        fi

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Fetch tags from master
      id: fetch_tags
      run: |
        git fetch --tags
        latest_tag=$(git tag --list 'v*' | sort -V | tail -n 1)
        echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV

    - name: Increment version minor
      id: increment_version
      run: |
        if [ -z "$LATEST_TAG" ]; then
          new_tag="v1.0"
        else
          IFS='.' read -r major minor <<< "${LATEST_TAG#v}"
          new_minor=$((minor + 1))
          new_tag="v${major}.${new_minor}"
        fi
        echo "NEW_TAG=${new_tag}" >> $GITHUB_ENV

    - name: Create and push new tag
      run: |
        git tag $NEW_TAG
        git push origin $NEW_TAG

    - name: Output new tag
      run: |
        echo "New tag created: $NEW_TAG"