name: Update Tag Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'release'

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check PAT Token
      run: |
        if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
          echo "PAT_TOKEN is empty or not set"
          exit 1
        else
          echo "PAT_TOKEN is set"
        fi

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Fetch tags from master
      id: fetch_tags
      run: |
        git fetch --tags
        latest_tag=$(git tag --list 'v*' | sort -V | tail -n 1)
        echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV

    - name: Increment major version and create release tag
      id: create_tag
      run: |
        latest_tag=${{ env.LATEST_TAG }}
        major_version=$(echo $latest_tag | awk -F. '{print $1}')
        new_tag="$((major_version + 1)).0-rc"
        echo "NEW_TAG=${new_tag}" >> $GITHUB_ENV

    - name: Create and push new tag
      run: |
        git tag $NEW_TAG
        git push origin $NEW_TAG

    - name: Output new tag
      run: |
        echo "New tag created: $NEW_TAG"