name: Update Terraform Docs

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  update-terraform-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3
      with:
        fetch-depth: 0

    - name: Set up Terraform Docs
      run: |
        wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
        tar -xzf terraform-docs-v0.16.0-linux-amd64.tar.gz
        sudo mv terraform-docs /usr/local/bin/
        terraform-docs --version
    
    - name: Check PAT Token
      run: |
        if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
          echo "PAT_TOKEN is empty or not set"
          exit 1
        else
          echo "PAT_TOKEN is set"
        fi

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Terraform Docs
      run: |
        terraform-docs markdown . > README.md
    
    - name: Clean up
      run: |
        rm terraform-docs-v0.16.0-linux-amd64.tar.gz

    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "Update Terraform docs in all directories"
        git push origin release
