name: Update Terraform Docs

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  update-terraform-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Terraform Docs
      run: |
        curl -Lo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/latest/download/terraform-docs-$(uname -s)-$(uname -m).tar.gz
        tar -xzf terraform-docs.tar.gz
        sudo mv terraform-docs /usr/local/bin/
        terraform-docs --version

    - name: Generate Terraform Docs for all directories
      run: |
        find . -type d -exec sh -c 'cd "{}" && if [ -f main.tf ]; then terraform-docs markdown table . > README.md; fi' \;

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "Update Terraform docs in all directories"
        git push origin release
